# Generated by Django 2.2.3 on 2019-07-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagenes',
            field=models.ImageField(upload_to='static'),
        ),
    ]
