# Generated by Django 2.2.3 on 2019-07-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='descripcion_imagen',
            field=models.TextField(),
        ),
    ]
