# Generated by Django 2.2.3 on 2019-07-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('titulo_agenda', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bajada_titulo_agenda', models.CharField(max_length=50)),
                ('texto_agenda', models.TextField()),
                ('imagen_agenda', models.ImageField(upload_to='static')),
                ('imagen_agenda_dos', models.ImageField(upload_to='static')),
                ('fechapublicacion_agenda', models.DateTimeField()),
            ],
        ),
    ]
